services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  lqg-bot:
    build: ../loquegasto-bot
    ports:
      - "9091:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - BACKEND_URL=http://lqg-backend:8080
      - PORT=8080
    depends_on:
      - redis
#  lqg-telegram:
#    build: ../loquegasto-telegram
#    environment:
#      - JWT_SECRET=${JWT_SECRET}
#      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
#      - BACKEND_URL=http://lqg-backend:8080
#      - EXPORTER_FILE_PATH=lqg-export
#      - REDIS_HOST=redis:6379
#      - PORT=8080
#    depends_on:
#      - redis